<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>Vestigium</Authors>
    <Company>Wilkinson Business</Company>
    <NeutralLanguage>en-US</NeutralLanguage>
    <VestigiumNetworkVersion>1.2.0</VestigiumNetworkVersion>
    <VestigiumAnalyticsVersion>1.0.1</VestigiumAnalyticsVersion>
    <VestigiumChartsVersion>1.0.2</VestigiumChartsVersion>
    <VestigiumLoggingVersion>1.7.1</VestigiumLoggingVersion>
    <VestigiumThemesVersion>1.0.2</VestigiumThemesVersion>
    <VestigiumControlsVersion>1.0.0</VestigiumControlsVersion>
    <VestigiumConvertersVersion>1.0.0</VestigiumConvertersVersion>
    <MicrosoftExtensionsDiVersion>10.0.0</MicrosoftExtensionsDiVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'Vestigium.Suite.Network.Documentation'">
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Vestigium.Suite.Network.Documentation'">
    <TargetFramework>net10.0</TargetFramework>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
