<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Vestigium\Suite\Network\DnsIQ\" />
    <Folder Include="Vestigium\Suite\Network\TraceIQ\" />
    <Folder Include="Vestigium\Suite\Network\ShareIQ\" />
    <Folder Include="Vestigium\Suite\Network\RouteIQ\" />
    <Folder Include="Vestigium\Suite\Network\ProbeHost\" />
    <Folder Include="Vestigium\Suite\Network\PingIQ\" />
    <Folder Include="Vestigium\Suite\Network\NicIQ\" />
  </ItemGroup>

</Project>
