<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Vestigium\**\*.md" />
    <Folder Include="Vestigium\Suite\Network\WPF\DnsIQ\" />
    <Folder Include="Vestigium\Suite\Network\WPF\Shell\" />
    <Folder Include="Vestigium\Suite\Network\WPF\TraceIQ\" />
    <Folder Include="Vestigium\Suite\Network\WPF\ShareIQ\" />
    <Folder Include="Vestigium\Suite\Network\WPF\RouteIQ\" />
    <Folder Include="Vestigium\Suite\Network\WPF\ProbeHost\" />
    <Folder Include="Vestigium\Suite\Network\WPF\PingIQ\" />
    <Folder Include="Vestigium\Suite\Network\WPF\NicIQ\" />
  </ItemGroup>
</Project>
