<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Vestigium.Suite.Network.ProbeHost</RootNamespace>
    <AssemblyName>Vestigium.Suite.Network.ProbeHost</AssemblyName>
    <ApplicationTitle>ProbeHost</ApplicationTitle>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vestigium.Suite.Network.Shell\Vestigium.Suite.Network.Shell.csproj" />
  </ItemGroup>
</Project>
