<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Vestigium.Suite.Network.DnsIQ</RootNamespace>
    <AssemblyName>DnsIQ</AssemblyName>
    <ApplicationTitle>DnsIQ</ApplicationTitle>
    <ApplicationIcon>Assets\DnsIQ.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vestigium.Suite.Network.Shell\Vestigium.Suite.Network.Shell.csproj" />
    <Resource Include="Assets\DnsIQ.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Vestigium.Themes" Version="$(VestigiumThemesVersion)" />
    <PackageReference Include="Vestigium.Controls" Version="$(VestigiumControlsVersion)" />
    <PackageReference Include="Vestigium.Controls.StatusBar" Version="$(VestigiumControlsVersion)" />
    <PackageReference Include="Vestigium.Controls.NumericUpDown" Version="$(VestigiumNumericUpDownVersion)" />
    <PackageReference Include="Vestigium.Controls.UnderConstruction" Version="$(VestigiumControlsVersion)" />
    <PackageReference Include="Vestigium.Converters" Version="$(VestigiumConvertersVersion)" />
    <PackageReference Include="Vestigium.Helpers.Analytics" Version="$(VestigiumAnalyticsVersion)" />
    <PackageReference Include="Vestigium.Helpers.Charts" Version="$(VestigiumChartsVersion)" />
  </ItemGroup>
</Project>
